### ISSUE TITLE
IndexError: index 20 is out of bounds for axis 0 with size 20

### ISSUE THREAD

**Issue by sanren99999** [nladuo/captcha-break#10]
Traceback (most recent call last):
  File "E:/WJ/machinelearning/captcha-break-master/weibo.cn/python/spliter/__main__.py", line 25, in <module>
    split_dataset()
  File "E:/WJ/machinelearning/captcha-break-master/weibo.cn/python/spliter/__main__.py", line 22, in split_dataset
    ispliter.split_and_save(im_path)
  File "E:\WJ\machinelearning\captcha-break-master\weibo.cn\python\spliter\spliter.py", line 55, in split_and_save
    letters = self.split_letters(filename)
  File "E:\WJ\machinelearning\captcha-break-master\weibo.cn\python\spliter\spliter.py", line 42, in split_letters
    image = self.clear_noise(image)
  File "E:\WJ\machinelearning\captcha-break-master\weibo.cn\python\spliter\spliter.py", line 62, in clear_noise
    clear_horizontal_noise_line(image)
  File "E:\WJ\machinelearning\captcha-break-master\weibo.cn\python\spliter\spliter.py", line 165, in clear_horizontal_noise_line
    if is_black(i, now_height+1, image):
  File "E:\WJ\machinelearning\captcha-break-master\weibo.cn\python\spliter\spliter.py", line 99, in is_black
    b = image[j, i][0]
  

I try to modify two place in file spliter.py as follow:

def is_black(i, j, image):
    try:
        im=image
        shape=im.shape
------------------
#         i=min( shape[1]-1,i )
        j=min( shape[0]-1,j )
---------------------------
        b = image[j, i][0]
        g = image[j, i][1]
        r = image[j, i][2]
        average = (int(r) + int(g) + int(b))/3
        if r < 244 and abs(average-b) < 4 and abs(average-g) < 4 and abs(average-r) < 4:
            return True
        return False
    except Exception  as e:
        print(e)

def get_horizontal_noise_line_width(image, now_height, now_width):
    end_width = now_width
---------------------------------------------------------------
#     **now_height=min(  image.shape[0]-1,now_height )
    now_width = min(image.shape[1] - 1, now_width)**
  ----------------------------------------------------------------

    while end_width < image.shape[1] \
            and image[now_height][end_width][0] < 12 \
            and image[now_height][end_width][1] < 12 \
            and image[now_height][end_width][2] < 12:

        # print(image[now_height][end_width][0],
        #       image[now_height][end_width][1],
        #       image[now_height][end_width][2])

        end_width += 1

    return end_width - now_width

**Comment by nladuo** [comment]
Thx your reporting, try the latest version.
