### ISSUE TITLE
No module named  'img_process'

### ISSUE THREAD

**Issue by jedai47** [nladuo/captcha-break#12]
'''bash
python3 train.py                                                                                                                                      1 ⨯
Traceback (most recent call last):
  File "/home/kali/captcha-break/jikexueyuan/python/trainer/train.py", line 4, in <module>
    from gen.gen_captcha import gen_dataset, load_templates
  File "/home/kali/captcha-break/jikexueyuan/python/trainer/gen/gen_captcha.py", line 3, in <module>
    from img_process import rotate_and_cut
ModuleNotFoundError: No module named 'img_process'
'''
Thanks a lot

**Comment by minghu6** [comment]
这个项目看起来起码两年没更新了居然还有人看。。。。。。

看起来就是个普通python3 import 路径的问题：

python3对模块导入做了更严格的限制，需要确立一个项目的根目录，然后以此为基础提供路径关系
原文 `from img_process import rotate_and_cut` 这个写法有问题，这假设了项目的根目录为`captcha-break/jikexueyuan/python/trainer/gen`，如果在trainer目录上运行代码，应该写作`from gen.img_process import rotate_and_cut`

当然也可以临时把`captcha-break/jikexueyuan/python/trainer/gen`加入python模块的搜索路径上，但看着很奇怪，不推荐
